using System;

namespace RDR2Trainer
{
	internal enum VehicleType
	{
		Airbaloon,//热气球
		Boat,//船
		Cannon,//加农炮
		TrainType,//火车
		Wagon //马车
	}

	internal enum PedType : byte
	{
		Horse = 0x01,
		Dog = 0x04,
		Fish = 0x02,
		OtherAnimal = 0x08,
		CutscenePerson = 0x81,
		YoungFemale = 0x82,
		MiddleFemale = 0x84,
		OldFemale = 0x88,
		YoungMale = 0x90,
		MiddleMale = 0xA0,
		OldMale = 0xC0,
		Misc = 0x0,
	}

	internal readonly struct PedInfo(string modelID, string name, PedType type) : IEquatable<PedInfo>
	{
		public readonly string ModelID = modelID;  //游戏内资源文件名
		public readonly string Name = name; //修改器显示的名称，翻译时候改这个字段就行
		public readonly PedType Type = type;

		public bool IsAnimal { get { return Type == PedType.Horse || Type == PedType.Dog || Type == PedType.Fish || Type == PedType.OtherAnimal; } }

		public bool IsHorse { get { return Type == PedType.Horse; } }

		public bool IsFish { get { return Type == PedType.Fish; } }

		public bool IsDog { get { return Type == PedType.Dog; } }

		public bool IsOtherAnimal { get { return Type == PedType.OtherAnimal; } }

		public bool IsPerson { get { return !IsAnimal; } }

		public bool IsCutscenePerson { get { return Type == PedType.CutscenePerson; } }

		public bool IsYoungFemale { get { return Type == PedType.YoungFemale; } }

		public bool IsMiddleFemale { get { return Type == PedType.MiddleFemale; } }

		public bool IsOldFemale { get { return Type == PedType.OldFemale; } }

		public bool IsYoungMale { get { return Type == PedType.YoungMale; } }

		public bool IsMiddleMale { get { return Type == PedType.MiddleMale; } }

		public bool IsOldMale { get { return Type == PedType.OldMale; } }

		public bool IsMisc { get { return Type == PedType.Misc; } }

		public bool Equals(PedInfo other)
		{
			return ModelID == other.ModelID && Name == other.Name && Type == other.Type;
		}
	}

	internal readonly struct ItemInfo(string modelID, string name)
	{
		public readonly string ModelID = modelID;  //游戏内资源文件名
		public readonly string Name = name; //修改器显示的名称，翻译时候改这个字段就行
	}

	internal class ResourcesConfig
	{
		public static readonly PedInfo[] PedInfos = [
			new ("A_C_ALLIGATOR_01", "美国短吻鳄", PedType.OtherAnimal),
			new ("A_C_ALLIGATOR_02", "美国短吻鳄 2", PedType.OtherAnimal),
			new ("A_C_ALLIGATOR_03", "美国短吻鳄 3", PedType.OtherAnimal),
			new ("A_C_ARMADILLO_01", "九带犰狳", PedType.OtherAnimal),
			new ("A_C_BADGER_01", "美国獾", PedType.OtherAnimal),
			new ("A_C_BAT_01", "蝙蝠", PedType.OtherAnimal),
			new ("A_C_BEAR_01", "大灰熊", PedType.OtherAnimal),
			new ("A_C_BEARBLACK_01", "黑熊", PedType.OtherAnimal),
			new ("A_C_BEAVER_01", "河狸", PedType.OtherAnimal),
			new ("A_C_BIGHORNRAM_01", "盘羊", PedType.OtherAnimal),
			new ("A_C_BLUEJAY_01", "蓝松鸦", PedType.OtherAnimal),
			new ("A_C_BOAR_01", "野猪", PedType.OtherAnimal),
			new ("A_C_BUCK_01", "白尾公鹿", PedType.OtherAnimal),
			new ("A_C_BUFFALO_01", "野牛", PedType.OtherAnimal),
			new ("A_C_BULL_01", "公牛", PedType.OtherAnimal),
			new ("A_C_CALIFORNIACONDOR_01", "加州神鹭", PedType.OtherAnimal),
			new ("A_C_CARDINAL_01", "北美红雀", PedType.OtherAnimal),
			new ("A_C_CAROLINAPARAKEET_01", "卡莱罗纳长尾鹦鹉", PedType.OtherAnimal),
			new ("A_C_CAT_01", "美国家猫", PedType.OtherAnimal),
			new ("A_C_CEDARWAXWING_01", "雪松太平鸟", PedType.OtherAnimal),
			new ("A_C_CHICKEN_01", "多米尼克鸡", PedType.OtherAnimal),
			new ("A_C_CHIPMUNK_01", "西部花鼠", PedType.OtherAnimal),
			new ("A_C_CORMORANT_01", "双冠鸬鹚", PedType.OtherAnimal),
			new ("A_C_COUGAR_01", "美洲狮", PedType.OtherAnimal),
			new ("A_C_COW", "奶牛", PedType.OtherAnimal),
			new ("A_C_COYOTE_01", "郊狼", PedType.OtherAnimal),
			new ("A_C_CRAB_01", "古巴陆蟹", PedType.OtherAnimal),
			new ("A_C_CRANEWHOOPING_01", "美洲鹤", PedType.OtherAnimal),
			new ("A_C_CROW_01", "乌鸦", PedType.OtherAnimal),
			new ("A_C_DEER_01", "白尾鹿", PedType.OtherAnimal),
			new ("A_C_DOGAMERICANFOXHOUND_01", "美国猎狐犬", PedType.Dog),
			new ("A_C_DOGAUSTRALIANSHEPERD_01", "澳洲牧羊犬", PedType.Dog),
			new ("A_C_DOGBLUETICKCOONHOUND_01", "蓝斑浣熊猎犬", PedType.Dog),
			new ("A_C_DOGCATAHOULACUR_01", "卡他豪拉豹犬", PedType.Dog),
			new ("A_C_DOGCHESBAYRETRIEVER_01", "切萨皮克海湾寻回犬", PedType.Dog),
			new ("A_C_DOGCOLLIE_01", "边境牧羊犬", PedType.Dog),
			new ("A_C_DOGHOBO_01", "患疥藓的蓝斑浣熊猎犬", PedType.Dog),
			new ("A_C_DOGHOUND_01", "寻血猎犬", PedType.Dog),
			new ("A_C_DOGHUSKY_01", "哈士奇", PedType.Dog),
			new ("A_C_DOGLAB_01", "拉布拉多", PedType.Dog),
			new ("A_C_DOGPOODLE_01", "贵宾犬", PedType.Dog),
			new ("A_C_DOGRUFUS_01", "鲁弗斯", PedType.Dog),
			new ("A_C_DOGSTREET_01", "杂种犬", PedType.Dog),
			new ("A_C_DONKEY_01", "驴", PedType.OtherAnimal),
			new ("A_C_DUCK_01", "绿头鸭", PedType.OtherAnimal),
			new ("A_C_EAGLE_01", "白头雕", PedType.OtherAnimal),
			new ("A_C_EGRET_01", "棕颈鹭", PedType.OtherAnimal),
			new ("A_C_ELK_01", "母麋鹿", PedType.OtherAnimal),
			new ("A_C_FISHBLUEGIL_01_MS", "蓝鳃太阳鱼 大", PedType.Fish),
			new ("A_C_FISHBLUEGIL_01_SM", "蓝鳃太阳鱼 小", PedType.Fish),
			new ("A_C_FISHBULLHEADCAT_01_MS", "褐首鲇 大", PedType.Fish),
			new ("A_C_FISHBULLHEADCAT_01_SM", "褐首鲇 小", PedType.Fish),
			new ("A_C_FISHCHAINPICKEREL_01_SM", "暗色狗鱼 小", PedType.Fish),
			new ("A_C_FISHCHANNELCATFISH_01_LG", "暗色狗鱼 大", PedType.Fish),
			new ("A_C_FISHLAKESTURGEON_01_LG", "湖鲟", PedType.Fish),
			new ("A_C_FISHLARGEMOUTHBASS_01_LG", "大口黑鲈 大", PedType.Fish),
			new ("A_C_FISHLARGEMOUTHBASS_01_MS", "大口黑鲈 小", PedType.Fish),
			new ("A_C_FISHLONGNOSEGAR_01_LG", "长吻雀鳝", PedType.Fish),
			new ("A_C_FISHMUSKIE_01_LG", "北美狗鱼", PedType.Fish),
			new ("A_C_FISHNORTHERNPIKE_01_LG", "白斑狗鱼", PedType.Fish),
			new ("A_C_FISHPERCH_01_MS", "河鲈 大", PedType.Fish),
			new ("A_C_FISHPERCH_01_SM", "河鲈 小", PedType.Fish),
			new ("A_C_FISHRAINBOWTROUT_01_LG", "虹鳟鱼 大", PedType.Fish),
			new ("A_C_FISHRAINBOWTROUT_01_MS", "虹鳟鱼 小", PedType.Fish),
			new ("A_C_FISHREDFINPICKEREL_01_MS", "带纹狗鱼 大", PedType.Fish),
			new ("A_C_FISHREDFINPICKEREL_01_SM", "带纹狗鱼 小", PedType.Fish),
			new ("A_C_FISHROCKBASS_01_MS", "岩钝鲈鱼 大", PedType.Fish),
			new ("A_C_FISHROCKBASS_01_SM", "岩钝鲈鱼 小", PedType.Fish),
			new ("A_C_FISHSALMONSOCKEYE_01_LG", "红鲑鱼 大", PedType.Fish),
			new ("A_C_FISHSALMONSOCKEYE_01_MS", "红鲑鱼 小", PedType.Fish),
			new ("A_C_FISHSMALLMOUTHBASS_01_LG", "小口黑鲈 大", PedType.Fish),
			new ("A_C_FISHSMALLMOUTHBASS_01_MS", "小口黑鲈 小", PedType.Fish),
			new ("A_C_FOX_01", "红狐", PedType.OtherAnimal),
			new ("A_C_FROGBULL_01", "牛蛙", PedType.OtherAnimal),
			new ("A_C_GILAMONSTER_01", "带纹吉拉毒蜥蜴", PedType.OtherAnimal),
			new ("A_C_GOAT_01", "山羊", PedType.OtherAnimal),
			new ("A_C_GOOSECANADA_01", "加拿大大雁", PedType.OtherAnimal),
			new ("A_C_HAWK_01", "褐羽隼鹰", PedType.OtherAnimal),
			new ("A_C_HERON_01", "大蓝鹭", PedType.OtherAnimal),
			new ("A_C_HORSE_AMERICANPAINT_GREYOVERO", "美国花马 greyovero", PedType.Horse),
			new ("A_C_HORSE_AMERICANPAINT_OVERO", "美国花马 overo", PedType.Horse),
			new ("A_C_HORSE_AMERICANPAINT_SPLASHEDWHITE", "美国花马 splashedwhite", PedType.Horse),
			new ("A_C_HORSE_AMERICANPAINT_TOBIANO", "美国花马 tobiano", PedType.Horse),
			new ("A_C_HORSE_AMERICANSTANDARDBRED_BLACK", "美国标准种马 black", PedType.Horse),
			new ("A_C_HORSE_AMERICANSTANDARDBRED_BUCKSKIN", "美国标准种马 buckskin", PedType.Horse),
			new ("A_C_HORSE_AMERICANSTANDARDBRED_PALOMINODAPPLE", "美国标准种马 palominodapple", PedType.Horse),
			new ("A_C_HORSE_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN", "美国标准种马 silvertailbuckskin", PedType.Horse),
			new ("A_C_HORSE_ANDALUSIAN_DARKBAY", "安达卢西亚马 darkbay", PedType.Horse),
			new ("A_C_HORSE_ANDALUSIAN_ROSEGRAY", "安达卢西亚马 rosegray", PedType.Horse),
			new ("A_C_HORSE_APPALOOSA_BLANKET", "阿帕卢萨马 blanket", PedType.Horse),
			new ("A_C_HORSE_APPALOOSA_BROWNLEOPARD", "阿帕卢萨马 brownleopard", PedType.Horse),
			new ("A_C_HORSE_APPALOOSA_LEOPARD", "阿帕卢萨马 leopard", PedType.Horse),
			new ("A_C_HORSE_APPALOOSA_LEOPARDBLANKET", "阿帕卢萨马 leopardblanket", PedType.Horse),
			new ("A_C_HORSE_ARABIAN_BLACK", "阿拉伯马 black", PedType.Horse),
			new ("A_C_HORSE_ARABIAN_ROSEGREYBAY", "阿拉伯马 rosegreybay", PedType.Horse),
			new ("A_C_HORSE_ARABIAN_WHITE", "阿拉伯马 white", PedType.Horse),
			new ("A_C_HORSE_ARDENNES_BAYROAN", "阿尔登马 bayroan", PedType.Horse),
			new ("A_C_HORSE_ARDENNES_STRAWBERRYROAN", "阿尔登马 strawberryroan", PedType.Horse),
			new ("A_C_HORSE_BELGIAN_BLONDCHESTNUT", "比利时挽马 blondchestnut", PedType.Horse),
			new ("A_C_HORSE_BELGIAN_MEALYCHESTNUT", "比利时挽马 mealychestnut", PedType.Horse),
			new ("A_C_HORSE_DUTCHWARMBLOOD_CHOCOLATEROAN", "荷兰温血马 chocolateroan", PedType.Horse),
			new ("A_C_HORSE_DUTCHWARMBLOOD_SEALBROWN", "荷兰温血马 sealbrown", PedType.Horse),
			new ("A_C_HORSE_DUTCHWARMBLOOD_SOOTYBUCKSKIN", "荷兰温血马 sootybuckskin", PedType.Horse),
			new ("A_C_HORSE_GANG_BILL", "比尔的马", PedType.Horse),
			new ("A_C_HORSE_GANG_CHARLES", "查尔斯的马", PedType.Horse),
			new ("A_C_HORSE_GANG_CHARLES_ENDLESSSUMMER", "查尔斯的马 endlesssummer", PedType.Horse),
			new ("A_C_HORSE_GANG_DUTCH", "达奇的马", PedType.Horse),
			new ("A_C_HORSE_GANG_HOSEA", "何西阿的马", PedType.Horse),
			new ("A_C_HORSE_GANG_JAVIER", "加维尔的马", PedType.Horse),
			new ("A_C_HORSE_GANG_JOHN", "约翰的马", PedType.Horse),
			new ("A_C_HORSE_GANG_KAREN", "凯伦的马", PedType.Horse),
			new ("A_C_HORSE_GANG_KIERAN", "基兰的马", PedType.Horse),
			new ("A_C_HORSE_GANG_LENNY", "兰尼的马", PedType.Horse),
			new ("A_C_HORSE_GANG_MICAH", "麦卡的马", PedType.Horse),
			new ("A_C_HORSE_GANG_SADIE", "莎迪的马", PedType.Horse),
			new ("A_C_HORSE_GANG_SADIE_ENDLESSSUMMER", "莎迪的马 endlesssummer", PedType.Horse),
			new ("A_C_HORSE_GANG_SEAN", "西恩的马", PedType.Horse),
			new ("A_C_HORSE_GANG_TRELAWNEY", "特伦老尼的马", PedType.Horse),
			new ("A_C_HORSE_GANG_UNCLE", "大叔的马", PedType.Horse),
			new ("A_C_HORSE_GANG_UNCLE_ENDLESSSUMMER", "大叔的马 endlesssummer", PedType.Horse),
			new ("A_C_HORSE_HUNGARIANHALFBRED_DARKDAPPLEGREY", "匈牙利混种马 darkdapplegrey", PedType.Horse),
			new ("A_C_HORSE_HUNGARIANHALFBRED_FLAXENCHESTNUT", "匈牙利混种马 flaxenchestnut", PedType.Horse),
			new ("A_C_HORSE_HUNGARIANHALFBRED_PIEBALDTOBIANO", "匈牙利混种马 piebaldtobiano", PedType.Horse),
			new ("A_C_HORSE_KENTUCKYSADDLE_BLACK", "肯塔基骑乘马 black", PedType.Horse),
			new ("A_C_HORSE_KENTUCKYSADDLE_CHESTNUTPINTO", "肯塔基骑乘马 chestnutpinto", PedType.Horse),
			new ("A_C_HORSE_KENTUCKYSADDLE_GREY", "肯塔基骑乘马 grey", PedType.Horse),
			new ("A_C_HORSE_KENTUCKYSADDLE_SILVERBAY", "肯塔基骑乘马 silverbay", PedType.Horse),
			new ("A_C_HORSE_MISSOURIFOXTROTTER_AMBERCHAMPAGNE", "密苏里狐步马 amberchampagne", PedType.Horse),
			new ("A_C_HORSE_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO", "密苏里狐步马 silverdapplepinto", PedType.Horse),
			new ("A_C_HORSE_MORGAN_BAY", "摩根马 bay", PedType.Horse),
			new ("A_C_HORSE_MORGAN_BAYROAN", "摩根马 bayroan", PedType.Horse),
			new ("A_C_HORSE_MORGAN_FLAXENCHESTNUT", "摩根马 flaxenchestnut", PedType.Horse),
			new ("A_C_HORSE_MORGAN_PALOMINO", "摩根马 palomino", PedType.Horse),
			new ("A_C_HORSE_MUSTANG_GRULLODUN", "美洲野马 grullodun", PedType.Horse),
			new ("A_C_HORSE_MUSTANG_TIGERSTRIPEDBAY", "美洲野马 tigerstripedbay", PedType.Horse),
			new ("A_C_HORSE_MUSTANG_WILDBAY", "美洲野马 wildbay", PedType.Horse),
			new ("A_C_HORSE_NOKOTA_BLUEROAN", "北达科他马 blueroan", PedType.Horse),
			new ("A_C_HORSE_NOKOTA_REVERSEDAPPLEROAN", "北达科他马 reversedappleroan", PedType.Horse),
			new ("A_C_HORSE_NOKOTA_WHITEROAN", "北达科他马 whiteroan", PedType.Horse),
			new ("A_C_HORSE_SHIRE_DARKBAY", "夏尔马 darkbay", PedType.Horse),
			new ("A_C_HORSE_SHIRE_LIGHTGREY", "夏尔马 lightgrey", PedType.Horse),
			new ("A_C_HORSE_SUFFOLKPUNCH_REDCHESTNUT", "萨福克马 redchestnut", PedType.Horse),
			new ("A_C_HORSE_SUFFOLKPUNCH_SORREL", "萨福克马 sorrel", PedType.Horse),
			new ("A_C_HORSE_TENNESSEEWALKER_BLACKRABICANO", "西纳走田马 blackrabicano", PedType.Horse),
			new ("A_C_HORSE_TENNESSEEWALKER_CHESTNUT", "西纳走田马 chestnut", PedType.Horse),
			new ("A_C_HORSE_TENNESSEEWALKER_DAPPLEBAY", "西纳走田马 dapplebay", PedType.Horse),
			new ("A_C_HORSE_TENNESSEEWALKER_FLAXENROAN", "西纳走田马 flaxenroan", PedType.Horse),
			new ("A_C_HORSE_TENNESSEEWALKER_REDROAN", "西纳走田马 redroan", PedType.Horse),
			new ("A_C_HORSE_THOROUGHBRED_BLOODBAY", "纯血马 bloodbay", PedType.Horse),
			new ("A_C_HORSE_THOROUGHBRED_BRINDLE", "纯血马 brindle", PedType.Horse),
			new ("A_C_HORSE_THOROUGHBRED_DAPPLEGREY", "纯血马 dapplegrey", PedType.Horse),
			new ("A_C_HORSE_TURKOMAN_DARKBAY", "土库曼马 darkbay", PedType.Horse),
			new ("A_C_HORSE_TURKOMAN_GOLD", "土库曼马 gold", PedType.Horse),
			new ("A_C_HORSE_TURKOMAN_SILVER", "土库曼马 silver", PedType.Horse),
			new ("A_C_HORSEMULE_01", "骡子", PedType.OtherAnimal),
			new ("A_C_IGUANA_01", "绿蜥蜴", PedType.OtherAnimal),
			new ("A_C_IGUANADESERT_01", "沙漠蜥蜴", PedType.OtherAnimal),
			new ("A_C_JAVELINA_01", "领西猯(野猪)", PedType.OtherAnimal),
			new ("A_C_LOON_01", "普通潜鸟", PedType.OtherAnimal),
			new ("A_C_MOOSE_01", "西部驼鹿", PedType.OtherAnimal),
			new ("A_C_MUSKRAT_01", "美国麝鼠", PedType.OtherAnimal),
			new ("A_C_ORIOLE_01", "黄鹂", PedType.OtherAnimal),
			new ("A_C_OWL_01", "大角鸮(猫头鹰)", PedType.OtherAnimal),
			new ("A_C_OX_01", "阉牛", PedType.OtherAnimal),
			new ("A_C_PANTHER_01", "山狮", PedType.OtherAnimal),
			new ("A_C_PARROT_01", "金刚鹦鹉", PedType.OtherAnimal),
			new ("A_C_PELICAN_01", "白鹈鹕", PedType.OtherAnimal),
			new ("A_C_PHEASANT_01", "环颈雉鸡", PedType.OtherAnimal),
			new ("A_C_PIG_01", "家猪", PedType.OtherAnimal),
			new ("A_C_PIGEON", "岩鸽", PedType.OtherAnimal),
			new ("A_C_POSSUM_01", "负鼠", PedType.OtherAnimal),
			new ("A_C_PRAIRIECHICKEN_01", "草原松鸡", PedType.OtherAnimal),
			new ("A_C_PRONGHORN_01", "母叉角羚", PedType.OtherAnimal),
			new ("A_C_QUAIL_01", "鹌鹑", PedType.OtherAnimal),
			new ("A_C_RABBIT_01", "野兔", PedType.OtherAnimal),
			new ("A_C_RACCOON_01", "浣熊", PedType.OtherAnimal),
			new ("A_C_RAT_01", "普通老鼠", PedType.OtherAnimal),
			new ("A_C_RAVEN_01", "西部渡鸦", PedType.OtherAnimal),
			new ("A_C_REDFOOTEDBOOBY_01", "红脚鲣鸟", PedType.OtherAnimal),
			new ("A_C_ROBIN_01", "知更鸟", PedType.OtherAnimal),
			new ("A_C_ROOSTER_01", "大公鸡", PedType.OtherAnimal),
			new ("A_C_ROSEATESPOONBILL_01", "玫瑰琵鹭", PedType.OtherAnimal),
			new ("A_C_SEAGULL_01", "银鸥", PedType.OtherAnimal),
			new ("A_C_SHARKHAMMERHEAD_01", "锤头鲨", PedType.OtherAnimal),
			new ("A_C_SHARKTIGER", "虎鲨", PedType.OtherAnimal),
			new ("A_C_SHEEP_01", "绵羊", PedType.OtherAnimal),
			new ("A_C_SKUNK_01", "臭鼬", PedType.OtherAnimal),
			new ("A_C_SNAKE_01", "西部鳞斑响尾蛇", PedType.OtherAnimal),
			new ("A_C_SNAKEBLACKTAILRATTLE_01", "黑尾响尾蛇", PedType.OtherAnimal),
			new ("A_C_SNAKEFERDELANCE_01", "三色矛头蝮蛇", PedType.OtherAnimal),
			new ("A_C_SNAKEREDBOA_01", "红尾蟒蛇", PedType.OtherAnimal),
			new ("A_C_SNAKEWATER_01", "水蛇", PedType.OtherAnimal),
			new ("A_C_SONGBIRD_01", "西部丽唐纳鸣鸟", PedType.OtherAnimal),
			new ("A_C_SPARROW_01", "美洲树雀鹀", PedType.OtherAnimal),
			new ("A_C_SQUIRREL_01", "灰松鼠", PedType.OtherAnimal),
			new ("A_C_TOAD_01", "癞蛤蟆", PedType.OtherAnimal),
			new ("A_C_TURKEY_01", "火鸡", PedType.OtherAnimal),
			new ("A_C_TURKEYWILD_01", "野火鸡", PedType.OtherAnimal),
			new ("A_C_TURTLESEA_01", "绿海龟", PedType.OtherAnimal),
			new ("A_C_TURTLESNAPPING_01", "鳄龟", PedType.OtherAnimal),
			new ("A_C_VULTURE_01", "火鸡秃鹫", PedType.OtherAnimal),
			new ("A_C_WOLF", "大灰狼 大", PedType.OtherAnimal),
			new ("A_C_WOLF_MEDIUM", "大灰狼 中", PedType.OtherAnimal),
			new ("A_C_WOLF_SMALL", "大灰狼 小", PedType.OtherAnimal),
			new ("A_C_WOODPECKER_01", "啄木鸟", PedType.OtherAnimal),
			new ("A_C_WOODPECKER_02", "啄木鸟 2", PedType.OtherAnimal),
			new ("A_F_M_ARMCHOLERACORPSE_01", "armcholeracorpse", PedType.MiddleFemale),
			new ("A_F_M_ARMTOWNFOLK_01", "armtownfolk", PedType.MiddleFemale),
			new ("A_F_M_ARMTOWNFOLK_02", "armtownfolk 2", PedType.MiddleFemale),
			new ("A_F_M_ASBTOWNFOLK_01", "asbtownfolk", PedType.MiddleFemale),
			new ("A_F_M_BIVFANCYTRAVELLERS_01", "bivfancytravellers", PedType.MiddleFemale),
			new ("A_F_M_BLWTOWNFOLK_01", "blwtownfolk", PedType.MiddleFemale),
			new ("A_F_M_BLWTOWNFOLK_02", "blwtownfolk 2", PedType.MiddleFemale),
			new ("A_F_M_BLWUPPERCLASS_01", "blwupperclass", PedType.MiddleFemale),
			new ("A_F_M_BTCHILLBILLY_01", "btchillbilly", PedType.MiddleFemale),
			new ("A_F_M_BTCOBESEWOMEN_01", "btcobesewomen", PedType.MiddleFemale),
			new ("A_F_M_BYNFANCYTRAVELLERS_01", "bynfancytravellers", PedType.MiddleFemale),
			new ("A_F_M_FAMILYTRAVELERS_WARM_01", "familytravelers warm", PedType.MiddleFemale),
			new ("A_F_M_GUATOWNFOLK_01", "guatownfolk", PedType.MiddleFemale),
			new ("A_F_M_HTLFANCYTRAVELLERS_01", "htlfancytravellers", PedType.MiddleFemale),
			new ("A_F_M_LAGTOWNFOLK_01", "lagtownfolk", PedType.MiddleFemale),
			new ("A_F_M_LOWERSDTOWNFOLK_01", "lowersdtownfolk", PedType.MiddleFemale),
			new ("A_F_M_LOWERSDTOWNFOLK_02", "lowersdtownfolk 2", PedType.MiddleFemale),
			new ("A_F_M_LOWERSDTOWNFOLK_03", "lowersdtownfolk 3", PedType.MiddleFemale),
			new ("A_F_M_LOWERTRAINPASSENGERS_01", "lowertrainpassengers", PedType.MiddleFemale),
			new ("A_F_M_MIDDLESDTOWNFOLK_01", "middlesdtownfolk", PedType.MiddleFemale),
			new ("A_F_M_MIDDLESDTOWNFOLK_02", "middlesdtownfolk 2", PedType.MiddleFemale),
			new ("A_F_M_MIDDLETRAINPASSENGERS_01", "middletrainpassengers", PedType.MiddleFemale),
			new ("A_F_M_NBXSLUMS_01", "nbxslums", PedType.MiddleFemale),
			new ("A_F_M_NBXUPPERCLASS_01", "nbxupperclass", PedType.MiddleFemale),
			new ("A_F_M_NBXWHORE_01", "nbxwhore", PedType.MiddleFemale),
			new ("A_F_M_RHDPROSTITUTE_01", "rhdprostitute", PedType.MiddleFemale),
			new ("A_F_M_RHDTOWNFOLK_01", "rhdtownfolk", PedType.MiddleFemale),
			new ("A_F_M_RHDTOWNFOLK_02", "rhdtownfolk 2", PedType.MiddleFemale),
			new ("A_F_M_RHDUPPERCLASS_01", "rhdupperclass", PedType.MiddleFemale),
			new ("A_F_M_RKRFANCYTRAVELLERS_01", "rkrfancytravellers", PedType.MiddleFemale),
			new ("A_F_M_SCLFANCYTRAVELLERS_01", "sclfancytravellers", PedType.MiddleFemale),
			new ("A_F_M_SDCHINATOWN_01", "sdchinatown", PedType.MiddleFemale),
			new ("A_F_M_SDFANCYWHORE_01", "sdfancywhore", PedType.MiddleFemale),
			new ("A_F_M_SDOBESEWOMEN_01", "sdobesewomen", PedType.MiddleFemale),
			new ("A_F_M_SDSLUMS_02", "sdslums 2", PedType.MiddleFemale),
			new ("A_F_M_STRTOWNFOLK_01", "strtownfolk", PedType.MiddleFemale),
			new ("A_F_M_TUMTOWNFOLK_01", "tumtownfolk", PedType.MiddleFemale),
			new ("A_F_M_TUMTOWNFOLK_02", "tumtownfolk 2", PedType.MiddleFemale),
			new ("A_F_M_UPPERTRAINPASSENGERS_01", "uppertrainpassengers", PedType.MiddleFemale),
			new ("A_F_M_VALPROSTITUTE_01", "valprostitute", PedType.MiddleFemale),
			new ("A_F_M_VALTOWNFOLK_01", "valtownfolk", PedType.MiddleFemale),
			new ("A_F_M_VHTPROSTITUTE_01", "vhtprostitute", PedType.MiddleFemale),
			new ("A_F_M_VHTTOWNFOLK_01", "vhttownfolk", PedType.MiddleFemale),
			new ("A_F_M_WAPTOWNFOLK_01", "waptownfolk", PedType.MiddleFemale),
			new ("A_F_O_BLWUPPERCLASS_01", "blwupperclass", PedType.OldFemale),
			new ("A_F_O_BTCHILLBILLY_01", "btchillbilly", PedType.OldFemale),
			new ("A_F_O_GUATOWNFOLK_01", "guatownfolk", PedType.OldFemale),
			new ("A_F_O_LAGTOWNFOLK_01", "lagtownfolk", PedType.OldFemale),
			new ("A_F_O_SDCHINATOWN_01", "sdchinatown", PedType.OldFemale),
			new ("A_F_O_SDUPPERCLASS_01", "sdupperclass", PedType.OldFemale),
			new ("A_F_O_WAPTOWNFOLK_01", "waptownfolk", PedType.OldFemale),
			new ("A_M_M_ARMCHOLERACORPSE_01", "armcholeracorpse", PedType.MiddleMale),
			new ("A_M_M_ARMTOWNFOLK_01", "armtownfolk", PedType.MiddleMale),
			new ("A_M_M_ARMTOWNFOLK_02", "armtownfolk 2", PedType.MiddleMale),
			new ("A_M_M_ASBMINER_01", "asbminer", PedType.MiddleMale),
			new ("A_M_M_ASBMINER_02", "asbminer 2", PedType.MiddleMale),
			new ("A_M_M_ASBMINER_03", "asbminer 3", PedType.MiddleMale),
			new ("A_M_M_ASBMINER_04", "asbminer 4", PedType.MiddleMale),
			new ("A_M_M_ASBTOWNFOLK_01", "asbtownfolk", PedType.MiddleMale),
			new ("A_M_M_BIVWORKER_01", "bivworker", PedType.MiddleMale),
			new ("A_M_M_BLWFOREMAN_01", "blwforeman", PedType.MiddleMale),
			new ("A_M_M_BLWLABORER_01", "blwlaborer", PedType.MiddleMale),
			new ("A_M_M_BLWLABORER_02", "blwlaborer 2", PedType.MiddleMale),
			new ("A_M_M_BLWOBESEMEN_01", "blwobesemen", PedType.MiddleMale),
			new ("A_M_M_BLWTOWNFOLK_01", "blwtownfolk", PedType.MiddleMale),
			new ("A_M_M_BLWUPPERCLASS_01", "blwupperclass", PedType.MiddleMale),
			new ("A_M_M_BTCHILLBILLY_01", "btchillbilly", PedType.MiddleMale),
			new ("A_M_M_BTCOBESEMEN_01", "btcobesemen", PedType.MiddleMale),
			new ("A_M_M_BYNFANCYTRAVELLERS_01", "bynfancytravellers", PedType.MiddleMale),
			new ("A_M_M_BYNROUGHTRAVELLERS_01", "bynroughtravellers", PedType.MiddleMale),
			new ("A_M_M_EMRFARMHAND_01", "emrfarmhand", PedType.MiddleMale),
			new ("A_M_M_GRIROUGHTRAVELLERS_01", "griroughtravellers", PedType.MiddleMale),
			new ("A_M_M_GUATOWNFOLK_01", "guatownfolk", PedType.MiddleMale),
			new ("A_M_M_HTLFANCYDRIVERS_01", "htlfancydrivers", PedType.MiddleMale),
			new ("A_M_M_HTLFANCYTRAVELLERS_01", "htlfancytravellers", PedType.MiddleMale),
			new ("A_M_M_HTLROUGHTRAVELLERS_01", "htlroughtravellers", PedType.MiddleMale),
			new ("A_M_M_JAMESONGUARD_01", "jamesonguard", PedType.MiddleMale),
			new ("A_M_M_LAGTOWNFOLK_01", "lagtownfolk", PedType.MiddleMale),
			new ("A_M_M_LOWERSDTOWNFOLK_01", "lowersdtownfolk", PedType.MiddleMale),
			new ("A_M_M_LOWERSDTOWNFOLK_02", "lowersdtownfolk 2", PedType.MiddleMale),
			new ("A_M_M_LOWERTRAINPASSENGERS_01", "lowertrainpassengers", PedType.MiddleMale),
			new ("A_M_M_MIDDLESDTOWNFOLK_01", "middlesdtownfolk", PedType.MiddleMale),
			new ("A_M_M_MIDDLESDTOWNFOLK_02", "middlesdtownfolk 2", PedType.MiddleMale),
			new ("A_M_M_MIDDLESDTOWNFOLK_03", "middlesdtownfolk 3", PedType.MiddleMale),
			new ("A_M_M_MIDDLETRAINPASSENGERS_01", "middletrainpassengers", PedType.MiddleMale),
			new ("A_M_M_NBXDOCKWORKERS_01", "nbxdockworkers", PedType.MiddleMale),
			new ("A_M_M_NBXLABORERS_01", "nbxlaborers", PedType.MiddleMale),
			new ("A_M_M_NBXSLUMS_01", "nbxslums", PedType.MiddleMale),
			new ("A_M_M_NBXUPPERCLASS_01", "nbxupperclass", PedType.MiddleMale),
			new ("A_M_M_NEAROUGHTRAVELLERS_01", "nearoughtravellers", PedType.MiddleMale),
			new ("A_M_M_RANCHER_01", "rancher", PedType.MiddleMale),
			new ("A_M_M_RANCHERTRAVELERS_WARM_01", "ranchertravelers warm", PedType.MiddleMale),
			new ("A_M_M_RHDFOREMAN_01", "rhdforeman", PedType.MiddleMale),
			new ("A_M_M_RHDOBESEMEN_01", "rhdobesemen", PedType.MiddleMale),
			new ("A_M_M_RHDTOWNFOLK_01", "rhdtownfolk", PedType.MiddleMale),
			new ("A_M_M_RHDTOWNFOLK_01_LABORER", "rhdtownfolk 01 laborer", PedType.MiddleMale),
			new ("A_M_M_RHDTOWNFOLK_02", "rhdtownfolk 2", PedType.MiddleMale),
			new ("A_M_M_RHDUPPERCLASS_01", "rhdupperclass", PedType.MiddleMale),
			new ("A_M_M_RKRFANCYDRIVERS_01", "rkrfancydrivers", PedType.MiddleMale),
			new ("A_M_M_RKRFANCYTRAVELLERS_01", "rkrfancytravellers", PedType.MiddleMale),
			new ("A_M_M_RKRROUGHTRAVELLERS_01", "rkrroughtravellers", PedType.MiddleMale),
			new ("A_M_M_SCLFANCYTRAVELLERS_01", "sclfancytravellers", PedType.MiddleMale),
			new ("A_M_M_SCLROUGHTRAVELLERS_01", "sclroughtravellers", PedType.MiddleMale),
			new ("A_M_M_SDCHINATOWN_01", "sdchinatown", PedType.MiddleMale),
			new ("A_M_M_SDDOCKFOREMAN_01", "sddockforeman", PedType.MiddleMale),
			new ("A_M_M_SDDOCKWORKERS_02", "sddockworkers 2", PedType.MiddleMale),
			new ("A_M_M_SDLABORERS_02", "sdlaborers 2", PedType.MiddleMale),
			new ("A_M_M_SDOBESEMEN_01", "sdobesemen", PedType.MiddleMale),
			new ("A_M_M_SDROUGHTRAVELLERS_01", "sdroughtravellers", PedType.MiddleMale),
			new ("A_M_M_SDSLUMS_02", "sdslums 2", PedType.MiddleMale),
			new ("A_M_M_SKPPRISONER_01", "skpprisoner", PedType.MiddleMale),
			new ("A_M_M_STRFANCYTOURIST_01", "strfancytourist", PedType.MiddleMale),
			new ("A_M_M_STRLABORER_01", "strlaborer", PedType.MiddleMale),
			new ("A_M_M_STRTOWNFOLK_01", "strtownfolk", PedType.MiddleMale),
			new ("A_M_M_TUMTOWNFOLK_01", "tumtownfolk", PedType.MiddleMale),
			new ("A_M_M_TUMTOWNFOLK_02", "tumtownfolk 2", PedType.MiddleMale),
			new ("A_M_M_UNIGUNSLINGER_01", "unigunslinger", PedType.MiddleMale),
			new ("A_M_M_UPPERTRAINPASSENGERS_01", "uppertrainpassengers", PedType.MiddleMale),
			new ("A_M_M_VALCRIMINALS_01", "valcriminals", PedType.MiddleMale),
			new ("A_M_M_VALFARMER_01", "valfarmer", PedType.MiddleMale),
			new ("A_M_M_VALLABORER_01", "vallaborer", PedType.MiddleMale),
			new ("A_M_M_VALTOWNFOLK_01", "valtownfolk", PedType.MiddleMale),
			new ("A_M_M_VALTOWNFOLK_02", "valtownfolk 2", PedType.MiddleMale),
			new ("A_M_M_VHTTHUG_01", "vhtthug", PedType.MiddleMale),
			new ("A_M_M_VHTTOWNFOLK_01", "vhttownfolk", PedType.MiddleMale),
			new ("A_M_M_WAPWARRIORS_01", "wapwarriors", PedType.MiddleMale),
			new ("A_M_O_BLWUPPERCLASS_01", "blwupperclass", PedType.OldMale),
			new ("A_M_O_BTCHILLBILLY_01", "btchillbilly", PedType.OldMale),
			new ("A_M_O_GUATOWNFOLK_01", "guatownfolk", PedType.OldMale),
			new ("A_M_O_LAGTOWNFOLK_01", "lagtownfolk", PedType.OldMale),
			new ("A_M_O_SDCHINATOWN_01", "sdchinatown", PedType.OldMale),
			new ("A_M_O_SDUPPERCLASS_01", "sdupperclass", PedType.OldMale),
			new ("A_M_O_WAPTOWNFOLK_01", "waptownfolk", PedType.OldMale),
			new ("A_M_Y_ASBMINER_01", "asbminer", PedType.YoungMale),
			new ("A_M_Y_ASBMINER_02", "asbminer 2", PedType.YoungMale),
			new ("A_M_Y_ASBMINER_03", "asbminer 3", PedType.YoungMale),
			new ("A_M_Y_ASBMINER_04", "asbminer 4", PedType.YoungMale),
			new ("A_M_Y_NBXSTREETKIDS_01", "nbxstreetkids", PedType.YoungMale),
			new ("A_M_Y_NBXSTREETKIDS_SLUMS_01", "nbxstreetkids slums", PedType.YoungMale),
			new ("A_M_Y_SDSTREETKIDS_SLUMS_02", "sdstreetkids slums 2", PedType.YoungMale),
			new ("CS_ABE", "戴帽子男人", PedType.CutscenePerson),
			new ("CS_ABERDEENPIGFARMER", "猪肉佬", PedType.CutscenePerson),
			new ("CS_ABERDEENSISTER", "妇女", PedType.CutscenePerson),
			new ("CS_ABIGAILROBERTS", "带头巾妇女", PedType.CutscenePerson),
			new ("CS_ANGUSGEDDES", "背带裤青年", PedType.CutscenePerson),
			new ("CS_ARCHIEDOWN", "夹克青年", PedType.CutscenePerson),
			new ("CS_BILLWILLIAMSON", "比尔", PedType.CutscenePerson),
			new ("CS_BLWPHOTOGRAPHER", "摄影师", PedType.CutscenePerson),
			new ("CS_CHARLESSMITH", "查尔斯", PedType.CutscenePerson),
			new ("CS_CLEET", "cleet", PedType.CutscenePerson),
			new ("CS_CREOLECAPTAIN", "creolecaptain", PedType.CutscenePerson),
			new ("CS_DAVIDGEDDES", "davidgeddes", PedType.CutscenePerson),
			new ("CS_DOROETHEAWICKLOW", "doroetheawicklow", PedType.CutscenePerson),
			new ("CS_DUNCANGEDDES", "duncangeddes", PedType.CutscenePerson),
			new ("CS_DUTCH", "达奇", PedType.CutscenePerson),
			new ("CS_EAGLEFLIES", "eagleflies", PedType.CutscenePerson),
			new ("CS_EDITHDOWN", "edithdown", PedType.CutscenePerson),
			new ("CS_EDMUNDLOWRY", "edmundlowry", PedType.CutscenePerson),
			new ("CS_GRIZZLEDJON", "grizzledjon", PedType.CutscenePerson),
			new ("CS_HOSEAMATTHEWS", "何西阿", PedType.CutscenePerson),
			new ("CS_JACKMARSTON", "小杰克", PedType.CutscenePerson),
			new ("CS_JACKMARSTON_TEEN", "大杰克", PedType.CutscenePerson),
			new ("CS_JAVIERESCUELLA", "哈维尔", PedType.CutscenePerson),
			new ("CS_JOE", "joe", PedType.CutscenePerson),
			new ("CS_JOHNMARSTON", "约翰", PedType.CutscenePerson),
			new ("CS_JOSIAHTRELAWNY", "josiahtrelawny", PedType.CutscenePerson),
			new ("CS_KAREN", "凯伦", PedType.CutscenePerson),
			new ("CS_KIERAN", "基兰", PedType.CutscenePerson),
			new ("CS_LENNY", "兰尼", PedType.CutscenePerson),
			new ("CS_LEOSTRAUSS", "施特劳斯", PedType.CutscenePerson),
			new ("CS_MARYBETH", "marybeth", PedType.CutscenePerson),
			new ("CS_MICAHBELL", "麦卡", PedType.CutscenePerson),
			new ("CS_MOLLYOSHEA", "莫丽", PedType.CutscenePerson),
			new ("CS_MRPEARSON", "皮尔森", PedType.CutscenePerson),
			new ("CS_MRSADLER", "莎迪", PedType.CutscenePerson),
			new ("CS_MRSGEDDES", "mrsgeddes", PedType.CutscenePerson),
			new ("CS_NICHOLASTIMMINS", "nicholastimmins", PedType.CutscenePerson),
			new ("CS_POISONWELLSHAMAN", "poisonwellshaman", PedType.CutscenePerson),
			new ("CS_REVSWANSON", "斯旺森牧师", PedType.CutscenePerson),
			new ("CS_SDDOCTOR_01", "sddoctor", PedType.CutscenePerson),
			new ("CS_SEAN", "西恩", PedType.CutscenePerson),
			new ("CS_SHERIFFFREEMAN", "警长", PedType.CutscenePerson),
			new ("CS_SUSANGRIMSHAW", "苏珊-格林姆肖恩", PedType.CutscenePerson),
			new ("CS_THOMASDOWN", "thomasdown", PedType.CutscenePerson),
			new ("CS_TILLY", "蒂丽", PedType.CutscenePerson),
			new ("CS_TOMDICKENS", "tomdickens", PedType.CutscenePerson),
			new ("CS_UNCLE", "大叔", PedType.CutscenePerson),
			new ("CS_VALSHERIFF", "瓦伦丁警长", PedType.CutscenePerson),
			new ("CS_WROBEL", "wrobel", PedType.CutscenePerson),
			new ("FEMALE_SKELETON", "female skeleton", PedType.Misc),
			new ("G_M_M_UNIBANDITOS_01", "unibanditos", PedType.MiddleMale),
			new ("G_M_M_UNIBRAITHWAITES_01", "unibraithwaites", PedType.MiddleMale),
			new ("G_M_M_UNIBRONTEGOONS_01", "unibrontegoons", PedType.MiddleMale),
			new ("G_M_M_UNICORNWALLGOONS_01", "unicornwallgoons", PedType.MiddleMale),
			new ("G_M_M_UNICRIMINALS_01", "unicriminals", PedType.MiddleMale),
			new ("G_M_M_UNICRIMINALS_02", "unicriminals 2", PedType.MiddleMale),
			new ("G_M_M_UNIDUSTER_01", "uniduster", PedType.MiddleMale),
			new ("G_M_M_UNIDUSTER_02", "uniduster 2", PedType.MiddleMale),
			new ("G_M_M_UNIDUSTER_03", "uniduster 3", PedType.MiddleMale),
			new ("G_M_M_UNIGRAYS_01", "unigrays", PedType.MiddleMale),
			new ("G_M_M_UNIINBRED_01", "uniinbred", PedType.MiddleMale),
			new ("G_M_M_UNIMOUNTAINMEN_01", "unimountainmen", PedType.MiddleMale),
			new ("G_M_O_UNIEXCONFEDS_01", "uniexconfeds", PedType.OldMale),
			new ("G_M_Y_UNIEXCONFEDS_01", "uniexconfeds", PedType.YoungMale),
			new ("PLAYER_THREE", "player three", PedType.Misc),
			new ("PLAYER_ZERO", "亚瑟", PedType.Misc),
			new ("RCSP_CALDERON_MALES_01", "rcsp calderon males 01", PedType.Misc),
			new ("RE_DEADBODIES_MALES_01", "re deadbodies males 01", PedType.Misc),
			new ("S_F_M_BWMWORKER_01", "bwmworker", PedType.MiddleFemale),
			new ("S_F_M_CGHWORKER_01", "cghworker", PedType.MiddleFemale),
			new ("S_F_M_MAPWORKER_01", "mapworker", PedType.MiddleFemale),
			new ("S_M_M_AMBIENTBLWPOLICE_01", "ambientblwpolice", PedType.MiddleMale),
			new ("S_M_M_AMBIENTLAWRURAL_01", "ambientlawrural", PedType.MiddleMale),
			new ("S_M_M_AMBIENTSDPOLICE_01", "ambientsdpolice", PedType.MiddleMale),
			new ("S_M_M_ARMY_01", "army", PedType.MiddleMale),
			new ("S_M_M_BANKCLERK_01", "bankclerk", PedType.MiddleMale),
			new ("S_M_M_BARBER_01", "barber", PedType.MiddleMale),
			new ("S_M_M_BLWCOWPOKE_01", "blwcowpoke", PedType.MiddleMale),
			new ("S_M_M_BWMWORKER_01", "bwmworker", PedType.MiddleMale),
			new ("S_M_M_CGHWORKER_01", "cghworker", PedType.MiddleMale),
			new ("S_M_M_CKTWORKER_01", "cktworker", PedType.MiddleMale),
			new ("S_M_M_CORNWALLGUARD_01", "cornwallguard", PedType.MiddleMale),
			new ("S_M_M_FUSSARHENCHMAN_01", "fussarhenchman", PedType.MiddleMale),
			new ("S_M_M_LIVERYWORKER_01", "liveryworker", PedType.MiddleMale),
			new ("S_M_M_MAGICLANTERN_01", "magiclantern", PedType.MiddleMale),
			new ("S_M_M_MAPWORKER_01", "mapworker", PedType.MiddleMale),
			new ("S_M_M_MARKETVENDOR_01", "marketvendor", PedType.MiddleMale),
			new ("S_M_M_RACRAILGUARDS_01", "racrailguards", PedType.MiddleMale),
			new ("S_M_M_RACRAILWORKER_01", "racrailworker", PedType.MiddleMale),
			new ("S_M_M_RHDCOWPOKE_01", "rhdcowpoke", PedType.MiddleMale),
			new ("S_M_M_SDCOWPOKE_01", "sdcowpoke", PedType.MiddleMale),
			new ("S_M_M_SDTICKETSELLER_01", "sdticketseller", PedType.MiddleMale),
			new ("S_M_M_SKPGUARD_01", "skpguard", PedType.MiddleMale),
			new ("S_M_M_STRLUMBERJACK_01", "strlumberjack", PedType.MiddleMale),
			new ("S_M_M_TAILOR_01", "tailor", PedType.MiddleMale),
			new ("S_M_M_TRAINSTATIONWORKER_01", "trainstationworker", PedType.MiddleMale),
			new ("S_M_M_TUMDEPUTIES_01", "tumdeputies", PedType.MiddleMale),
			new ("S_M_M_UNIBUTCHERS_01", "unibutchers", PedType.MiddleMale),
			new ("S_M_M_UNITRAINENGINEER_01", "unitrainengineer", PedType.MiddleMale),
			new ("S_M_M_UNITRAINGUARDS_01", "unitrainguards", PedType.MiddleMale),
			new ("S_M_M_VALCOWPOKE_01", "valcowpoke", PedType.MiddleMale),
			new ("S_M_Y_ARMY_01", "army", PedType.YoungMale),
			new ("S_M_Y_NEWSPAPERBOY_01", "newspaperboy", PedType.YoungMale),
			new ("S_M_Y_RACRAILWORKER_01", "racrailworker", PedType.YoungMale),
			new ("U_F_M_HTLWIFE_01", "htlwife", PedType.MiddleFemale),
			new ("U_F_M_LAGMOTHER_01", "lagmother", PedType.MiddleFemale),
			new ("U_F_M_RKSHOMESTEADTENANT_01", "rkshomesteadtenant", PedType.MiddleFemale),
			new ("U_F_M_TUMGENERALSTOREOWNER_01", "tumgeneralstoreowner", PedType.MiddleFemale),
			new ("U_F_M_VHTBARTENDER_01", "vhtbartender", PedType.MiddleFemale),
			new ("U_F_O_WTCTOWNFOLK_01", "wtctownfolk", PedType.OldFemale),
			new ("U_F_Y_CZPHOMESTEADDAUGHTER_01", "czphomesteaddaughter", PedType.YoungFemale),
			new ("U_M_M_ARMGENERALSTOREOWNER_01", "armgeneralstoreowner", PedType.MiddleMale),
			new ("U_M_M_ARMTRAINSTATIONWORKER_01", "armtrainstationworker", PedType.MiddleMale),
			new ("U_M_M_ARMUNDERTAKER_01", "armundertaker", PedType.MiddleMale),
			new ("U_M_M_ASBGUNSMITH_01", "asbgunsmith", PedType.MiddleMale),
			new ("U_M_M_BIVFOREMAN_01", "bivforeman", PedType.MiddleMale),
			new ("U_M_M_BLWTRAINSTATIONWORKER_01", "blwtrainstationworker", PedType.MiddleMale),
			new ("U_M_M_BWMSTABLEHAND_01", "bwmstablehand", PedType.MiddleMale),
			new ("U_M_M_CAJHOMESTEAD_01", "cajhomestead", PedType.MiddleMale),
			new ("U_M_M_CRDHOMESTEADTENANT_01", "crdhomesteadtenant", PedType.MiddleMale),
			new ("U_M_M_CRDHOMESTEADTENANT_02", "crdhomesteadtenant 2", PedType.MiddleMale),
			new ("U_M_M_CZPHOMESTEADFATHER_01", "czphomesteadfather", PedType.MiddleMale),
			new ("U_M_M_DORHOMESTEADHUSBAND_01", "dorhomesteadhusband", PedType.MiddleMale),
			new ("U_M_M_EMRFATHER_01", "emrfather", PedType.MiddleMale),
			new ("U_M_M_HHRRANCHER_01", "hhrrancher", PedType.MiddleMale),
			new ("U_M_M_HTLFOREMAN_01", "htlforeman", PedType.MiddleMale),
			new ("U_M_M_HTLHUSBAND_01", "htlhusband", PedType.MiddleMale),
			new ("U_M_M_LNSWORKER_01", "lnsworker", PedType.MiddleMale),
			new ("U_M_M_LNSWORKER_02", "lnsworker 2", PedType.MiddleMale),
			new ("U_M_M_LNSWORKER_03", "lnsworker 3", PedType.MiddleMale),
			new ("U_M_M_LNSWORKER_04", "lnsworker 4", PedType.MiddleMale),
			new ("U_M_M_LRSHOMESTEADTENANT_01", "lrshomesteadtenant", PedType.MiddleMale),
			new ("U_M_M_MFRRANCHER_01", "mfrrancher", PedType.MiddleMale),
			new ("U_M_M_NBXBARTENDER_01", "nbxbartender", PedType.MiddleMale),
			new ("U_M_M_NBXBARTENDER_02", "nbxbartender 2", PedType.MiddleMale),
			new ("U_M_M_NBXGENERALSTOREOWNER_01", "nbxgeneralstoreowner", PedType.MiddleMale),
			new ("U_M_M_NBXGUNSMITH_01", "nbxgunsmith", PedType.MiddleMale),
			new ("U_M_M_NBXSHADYDEALER_01", "nbxshadydealer", PedType.MiddleMale),
			new ("U_M_M_ORPGUARD_01", "orpguard", PedType.MiddleMale),
			new ("U_M_M_RACFOREMAN_01", "racforeman", PedType.MiddleMale),
			new ("U_M_M_RHDBARTENDER_01", "rhdbartender", PedType.MiddleMale),
			new ("U_M_M_RHDGENSTOREOWNER_01", "rhdgenstoreowner", PedType.MiddleMale),
			new ("U_M_M_RHDGENSTOREOWNER_02", "rhdgenstoreowner 2", PedType.MiddleMale),
			new ("U_M_M_RHDGUNSMITH_01", "rhdgunsmith", PedType.MiddleMale),
			new ("U_M_M_RHDSHERIFF_01", "rhdsheriff", PedType.MiddleMale),
			new ("U_M_M_RHDTRAINSTATIONWORKER_01", "rhdtrainstationworker", PedType.MiddleMale),
			new ("U_M_M_RKFRANCHER_01", "rkfrancher", PedType.MiddleMale),
			new ("U_M_M_SDPHOTOGRAPHER_01", "sdphotographer", PedType.MiddleMale),
			new ("U_M_M_SDPOLICECHIEF_01", "sdpolicechief", PedType.MiddleMale),
			new ("U_M_M_SDTRAPPER_01", "sdtrapper", PedType.MiddleMale),
			new ("U_M_M_STRFREIGHTSTATIONOWNER_01", "strfreightstationowner", PedType.MiddleMale),
			new ("U_M_M_STRGENSTOREOWNER_01", "strgenstoreowner", PedType.MiddleMale),
			new ("U_M_M_STRSHERRIFF_01", "strsherriff", PedType.MiddleMale),
			new ("U_M_M_STRWELCOMECENTER_01", "strwelcomecenter", PedType.MiddleMale),
			new ("U_M_M_TUMBARTENDER_01", "tumbartender", PedType.MiddleMale),
			new ("U_M_M_TUMBUTCHER_01", "tumbutcher", PedType.MiddleMale),
			new ("U_M_M_TUMGUNSMITH_01", "tumgunsmith", PedType.MiddleMale),
			new ("U_M_M_UNIEXCONFEDSBOUNTY_01", "uniexconfedsbounty", PedType.MiddleMale),
			new ("U_M_M_VALBARBER_01", "valbarber", PedType.MiddleMale),
			new ("U_M_M_VALBARTENDER_01", "valbartender", PedType.MiddleMale),
			new ("U_M_M_VALBUTCHER_01", "valbutcher", PedType.MiddleMale),
			new ("U_M_M_VALDOCTOR_01", "valdoctor", PedType.MiddleMale),
			new ("U_M_M_VALGENSTOREOWNER_01", "valgenstoreowner", PedType.MiddleMale),
			new ("U_M_M_VALGUNSMITH_01", "valgunsmith", PedType.MiddleMale),
			new ("U_M_M_VALHOTELOWNER_01", "valhotelowner", PedType.MiddleMale),
			new ("U_M_M_VHTSTATIONCLERK_01", "vhtstationclerk", PedType.MiddleMale),
			new ("U_M_M_WALGENERALSTOREOWNER_01", "walgeneralstoreowner", PedType.MiddleMale),
			new ("U_M_M_WAPOFFICIAL_01", "wapofficial", PedType.MiddleMale),
			new ("U_M_O_ARMBARTENDER_01", "armbartender", PedType.OldMale),
			new ("U_M_O_ASBSHERIFF_01", "asbsheriff", PedType.OldMale),
			new ("U_M_O_BLWBARTENDER_01", "blwbartender", PedType.OldMale),
			new ("U_M_O_BLWGENERALSTOREOWNER_01", "blwgeneralstoreowner", PedType.OldMale),
			new ("U_M_O_BLWPOLICECHIEF_01", "blwpolicechief", PedType.OldMale),
			new ("U_M_O_CAJHOMESTEAD_01", "cajhomestead", PedType.OldMale),
			new ("U_M_O_CMRCIVILWARCOMMANDO_01", "cmrcivilwarcommando", PedType.OldMale),
			new ("U_M_O_PSHRANCHER_01", "pshrancher", PedType.OldMale),
			new ("U_M_O_VALBARTENDER_01", "valbartender", PedType.OldMale),
			new ("U_M_O_VHTEXOTICSHOPKEEPER_01", "vhtexoticshopkeeper", PedType.OldMale),
			new ("U_M_Y_CAJHOMESTEAD_01", "cajhomestead", PedType.YoungMale),
			new ("U_M_Y_CZPHOMESTEADSON_01", "czphomesteadson", PedType.YoungMale),
			new ("U_M_Y_CZPHOMESTEADSON_02", "czphomesteadson 2", PedType.YoungMale),
			new ("U_M_Y_CZPHOMESTEADSON_03", "czphomesteadson 3", PedType.YoungMale),
			new ("U_M_Y_EMRSON_01", "emrson", PedType.YoungMale),
			new ("U_M_Y_HTLWORKER_01", "htlworker", PedType.YoungMale),
			new ("U_M_Y_HTLWORKER_02", "htlworker 2", PedType.YoungMale),
		];

		public static readonly ItemInfo[] VehicleInfos = [
			new ("gatling_gun", "加特林机枪"),
			new ("gatlingMaxim02", "马克沁重机枪"),
			new ("hotAirBalloon01", "热气球"),
			new ("hotchkiss_cannon", "火炮"),
			new ("breach_cannon", "意大利炮"),
			new ("privateopensleeper02x", "privateopensleeper02x"),
			new ("privateopensleeper01x", "privateopensleeper01x"),
			new ("STEAMERDUMMY", "STEAMERDUMMY"),
			new ("armoredCar01x", "armoredCar01x"),
			new ("armoredCar03x", "armoredCar03x"),
			new ("privatebaggage01x", "privatebaggage01x"),
			new ("smuggler02", "smuggler02"),
			new ("keelboat", "keelboat"),
			new ("boatSteam02x", "boatSteam02x"),
			new ("midlandrefrigeratorCar", "midlandrefrigeratorCar"),
			new ("midlandboxcar05x", "midlandboxcar05x"),
			new ("CABOOSE01X", "CABOOSE01X"),
			new ("canoe", "canoe"),
			new ("canoeTreeTrunk", "canoeTreeTrunk"),
			new ("cart01", "cart01"),
			new ("cart02", "cart02"),
			new ("cart03", "cart03"),
			new ("cart04", "cart04"),
			new ("cart05", "cart05"),
			new ("cart06", "cart06"),
			new ("cart07", "cart07"),
			new ("cart08", "cart08"),
			new ("coach2", "coach2"),
			new ("coach3", "coach3"),
			new ("coach3", "coach3"),
			new ("coach4", "coach4"),
			new ("coach5", "coach5"),
			new ("coach6", "coach6"),
			new ("cart06", "cart06"),
			new ("cart06", "cart06"),
			new ("buggy03", "buggy03"),
			new ("ArmySupplyWagon", "ArmySupplyWagon"),
			new ("chuckwagon000x", "chuckwagon000x"),
			new ("chuckwagon000x", "chuckwagon000x"),
			new ("chuckwagon000x", "chuckwagon000x"),
			new ("logwagon", "logwagon"),
			new ("logwagon2", "logwagon2"),
			new ("coal_wagon", "coal_wagon"),
			new ("chuckwagon002x", "chuckwagon002x"),
			new ("handcart", "handcart"),
			new ("horseBoat", "horseBoat"),
			new ("mineCart01x", "mineCart01x"),
			new ("northflatcar01x", "northflatcar01x"),
			new ("privateflatcar01x", "privateflatcar01x"),
			new ("northpassenger01x", "northpassenger01x"),
			new ("northpassenger03x", "northpassenger03x"),
			new ("privatepassenger01x", "privatepassenger01x"),
			new ("oilWagon01x", "oilWagon01x"),
			new ("oilWagon02x", "oilWagon02x"),
			new ("pirogue", "pirogue"),
			new ("pirogue2", "pirogue2"),
			new ("policeWagon01x", "policeWagon01x"),
			new ("policeWagongatling01x", "policeWagongatling01x"),
			new ("privateCoalCar01x", "privateCoalCar01x"),
			new ("NorthCoalCar01x", "NorthCoalCar01x"),
			new ("winterSteamer", "winterSteamer"),
			new ("wintercoalcar", "wintercoalcar"),
			new ("privateboxcar04x", "privateboxcar04x"),
			new ("privateboxcar02x", "privateboxcar02x"),
			new ("privateboxcar01x", "privateboxcar01x"),
			new ("coalHopper01x", "coalHopper01x"),
			new ("privateObservationcar", "privateObservationcar"),
			new ("privateArmoured", "privateArmoured"),
			new ("privateDining01x", "privateDining01x"),
			new ("privateRooms01x", "privateRooms01x"),
			new ("privateSteamer01x", "privateSteamer01x"),
			new ("northSteamer01x", "northSteamer01x"),
			new ("GhostTrainSteamer", "GhostTrainSteamer"),
			new ("GhostTrainCoalCar", "GhostTrainCoalCar"),
			new ("GhostTrainPassenger", "GhostTrainPassenger"),
			new ("GhostTrainCaboose", "GhostTrainCaboose"),
			new ("rcBoat", "rcBoat"),
			new ("rowboat", "rowboat"),
			new ("rowboatSwamp", "rowboatSwamp"),
			new ("rowboatSwamp02", "rowboatSwamp02"),
			new ("ship_guama02", "ship_guama02"),
			new ("turbineboat", "turbineboat"),
			new ("ship_nbdGuama", "ship_nbdGuama"),
			new ("ship_nbdGuama2", "ship_nbdGuama2"),
			new ("skiff", "skiff"),
			new ("stagecoach001x", "stagecoach001x"),
			new ("stagecoach002x", "stagecoach002x"),
			new ("stagecoach003x", "stagecoach003x"),
			new ("STAGECOACH004X", "STAGECOACH004X"),
			new ("stagecoach001x", "stagecoach001x"),
			new ("stagecoach006x", "stagecoach006x"),
			new ("TROLLEY01X", "TROLLEY01X"),
			new ("TugBoat2", "TugBoat2"),
			new ("wagon02x", "wagon02x"),
			new ("wagon03x", "wagon03x"),
			new ("wagon04x", "wagon04x"),
			new ("wagon05x", "wagon05x"),
			new ("wagon06x", "wagon06x"),
			new ("wagonCircus01x", "wagonCircus01x"),
			new ("wagonCircus02x", "wagonCircus02x"),
			new ("wagonDoc01x", "wagonDoc01x"),
			new ("wagonPrison01x", "wagonPrison01x"),
			new ("wagonWork01x", "wagonWork01x"),
			new ("wagonDairy01x", "wagonDairy01x"),
			new ("wagonTraveller01x", "wagonTraveller01x"),
			new ("utilliwag", "utilliwag"),
			new ("gatchuck", "gatchuck"),
			new ("gatchuck_2", "gatchuck_2"),
		];

		public static readonly ItemInfo[] WeaponInfos = [
			new ("WEAPON_PISTOL_MAUSER", "毛瑟手枪"),
			new ("WEAPON_PISTOL_M1899", "M1899"),
			new ("WEAPON_PISTOL_MAUSER_DRUNK", "米德奈特的毛瑟手枪"),
			new ("WEAPON_SHOTGUN_DOUBLEBARREL", "双管霰弹枪"),
			new ("WEAPON_SHOTGUN_SAWEDOFF", "削短型霰弹枪"),
			new ("WEAPON_SHOTGUN_SEMIAUTO", "半自动霰弹枪"),
			new ("WEAPON_SHOTGUN_REPEATING", "连发霰弹枪"),
			new ("WEAPON_SHOTGUN_PUMP", "泵动式霰弹枪"),
			new ("WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC", "稀有霰弹枪"),
			new ("WEAPON_REPEATER_CARBINE", "卡宾连发步枪"),
			new ("WEAPON_REPEATER_WINCHESTER", "蓝卡斯特连发步枪"),
			new ("WEAPON_REPEATER_HENRY", "利奇菲尔德连发步枪"),
			new ("WEAPON_RIFLE_SPRINGFIELD", "春田步枪"),
			new ("WEAPON_RIFLE_BOLTACTION", "拉栓式步枪"),
			new ("WEAPON_RIFLE_VARMINT", "捕猎步枪"),
			new ("WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC", "稀有滚轮闭锁式步枪"),
			new ("WEAPON_SNIPERRIFLE_CARCANO", "卡尔卡诺步枪"),
			new ("WEAPON_SNIPERRIFLE_ROLLINGBLOCK", "滚轮闭锁式步枪"),
			new ("WEAPON_REPEATER_EVANS", "埃文斯连发步枪"),
			new ("WEAPON_BOW", "弓"),
			new ("WEAPON_REVOLVER_DOUBLEACTION", "双动左轮"),
			new ("WEAPON_REVOLVER_CATTLEMAN_JOHN", "约翰的左轮"),
			new ("WEAPON_REVOLVER_CATTLEMAN_MEXICAN", "弗拉科的左轮"),
			new ("WEAPON_REVOLVER_CATTLEMAN_PIG", "格兰杰的左轮"),
			new ("WEAPON_REVOLVER_DOUBLEACTION_MICAH", "麦卡的左轮"),
			new ("WEAPON_REVOLVER_DOUBLEACTION_GAMBLER", "豪客左轮"),
			new ("WEAPON_REVOLVER_DOUBLEACTION_EXOTIC", "阿尔杰农的左轮"),
			new ("WEAPON_REVOLVER_SCHOFIELD_CALLOWAY", "卡洛威的左轮"),
			new ("WEAPON_REVOLVER_SCHOFIELD_GOLDEN", "奥蒂斯·米勒的左轮"),
			new ("WEAPON_REVOLVER_LEMAT", "勒马特左轮"),
			new ("WEAPON_REVOLVER_SCHOFIELD", "斯科菲尔德左轮"),
			new ("WEAPON_PISTOL_VOLCANIC", "火山手枪"),
			new ("WEAPON_PISTOL_SEMIAUTO", "半自动手枪"),
			new ("WEAPON_MELEE_KNIFE_JAWBONE", "颚骨刀"),
			new ("WEAPON_MELEE_KNIFE_JOHN", "约翰的刀"),
			new ("WEAPON_MELEE_KNIFE_MINER", "宽刃刀"),
			new ("WEAPON_MELEE_KNIFE_VAMPIRE", "装饰华丽的匕首"),
			new ("WEAPON_MELEE_KNIFE_BEAR", "角柄刀"),
			new ("WEAPON_MELEE_HATCHET_VIKING", "维京短斧"),
			new ("WEAPON_MELEE_HATCHET_HEWING", "劈砍短斧"),
			new ("WEAPON_MELEE_HATCHET_HUNTER", "猎人短斧"),
			new ("WEAPON_MELEE_HATCHET_HUNTER_RUSTED", "生锈的猎人短斧"),
			new ("WEAPON_MELEE_HATCHET_DOUBLE_BIT", "双头短斧"),
			new ("WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED", "生锈的双头短斧"),
			new ("WEAPON_THROWN_TOMAHAWK_ANCIENT", "古代手斧"),	
			new ("WEAPON_MELEE_BROKEN_SWORD", "断剑"),
			new ("WEAPON_MELEE_KNIFE_CIVIL_WAR", "内战刀"),
			new ("WEAPON_MELEE_ANCIENT_HATCHET", "古斧"),
			new ("WEAPON_REVOLVER_CATTLEMAN", "牛仔左轮"),
			new ("WEAPON_THROWN_DYNAMITE", "炸药"),
			new ("WEAPON_THROWN_DYNAMITE_VOLATILE", "烈性炸药"),
			new ("WEAPON_THROWN_MOLOTOV", "燃烧瓶"),
			new ("WEAPON_THROWN_MOLOTOV_VOLATILE", "烈性燃烧瓶"),
			new ("WEAPON_THROWN_THROWING_KNIVES", "飞刀"),
			new ("WEAPON_THROWN_TOMAHAWK", "飞斧"),
			new ("WEAPON_KIT_BINOCULARS", "望远镜"),
			new ("WEAPON_LASSO", "绳套"),
			new ("WEAPON_KIT_CAMERA", "照相机"),
			new ("WEAPON_FISHINGROD", "钓鱼竿"),
			new ("WEAPON_MOONSHINEJUG", "私酒"),
			new ("WEAPON_MELEE_CLEAVER", "砍刀"),
			new ("WEAPON_MELEE_HATCHET", "斧头"),
			new ("WEAPON_MELEE_KNIFE", "小刀"),
			new ("WEAPON_MELEE_MACHETE", "大砍刀"),
			new ("WEAPON_MELEE_TORCH", "火把"),
			new ("WEAPON_MELEE_LANTERN", "油灯1"),
			new ("WEAPON_MELEE_DAVY_LANTERN", "油灯2"),
			new ("WEAPON_MELEE_LANTERN_ELECTRIC", "油灯3"),
		];

		public static readonly ItemInfo[] WeatherInfos = [
			new ("SUNNY", "晴天"),
			new ("MISTY", "薄雾"),
			new ("FOG", "浓雾"),
			new ("CLOUDS", "多云"),
			new ("OVERCAST", "阴天"),
			new ("OVERCASTDARK", "乌云密布"),
			new ("DRIZZLE", "毛毛雨"),
			new ("RAIN", "小雨"),
			new ("THUNDER", "打雷"),
			new ("THUNDERSTORM", "雷雨交加"),
			new ("HURRICANE", "飓风"),
			new ("HIGHPRESSURE", "高压"),
			new ("SHOWER", "阵雨"),
			new ("HAIL", "冰雹"),
			new ("SLEET", "雨夹雪"),
			new ("SNOWCLEARING", "停止下雪"),
			new ("SNOWLIGHT", "下雪之夜"),
			new ("SNOW", "下雪"),
			new ("BLIZZARD", "暴风雪"),
			new ("GROUNDBLIZZARD", "地面暴风雪"),
			new ("WHITEOUT", "乳白天空"),
			new ("SANDSTORM", "沙尘暴"),
		];
	}
}
